#!/usr/bin/env python3
"""Emit the paper's Coin-* domain roster straight from domains.py.

Generated rather than hand-written so the table cannot drift from the registry the datasets were
actually built with -- the numbers in the paper are the numbers the model saw.

    python make_domain_table.py > ../../paper/ICLR/tables/exp3d_domains.tex
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT.parent / "dag_family"))

from domains import ALL_DOMAINS, TRAIN_POOL  # noqa: E402


def _tex(s: str) -> str:
    return s.replace("_", r"\_").replace("%", r"\%")


def main() -> None:
    """Columns are the affine skin itself -- offset, observable scale, driver scale -- so the
    reader can check that the implied sensitivity is exactly (s_d / i_d) * g_canonical and see
    where each domain's numbers come from."""
    rows = []
    for d in ALL_DOMAINS:
        role = "train" if d in TRAIN_POOL else r"\textbf{held out}"
        g0, g1 = d.g_disp_range
        rng = f"{d.fmt_output(d.out_lo)}--{d.fmt_output(d.out_hi)}"
        rows.append(
            f"\\texttt{{{_tex(d.label)}}} & {role} & "
            f"{_tex(d.output_name)} ({_tex(d.output_unit)}) & {rng} & "
            f"{d.offset:g} & {d.obs_scale:g} & {d.in_scale:g} & "
            f"{d.sigma_y_disp:.1f} & {g0:.2f}--{g1:.2f} \\\\")

    print("% generated by exp3_training_transfer/domain_family/make_domain_table.py "
          "-- do not edit")
    print(r"\begin{tabular}{l l l r r r r r c}")
    print(r"\toprule")
    print(r" & & \multicolumn{2}{c}{Observable} & \multicolumn{3}{c}{Display skin} & & \\")
    print(r"\cmidrule(lr){3-4}\cmidrule(lr){5-7}")
    print(r"Domain & Role & what & range & offset $o_d$ & scale $s_d$ & driver $i_d$"
          r" & noise $\sigma$ & sensitivity $g$ \\")
    print(r"\midrule")
    print("\n".join(rows[:len(TRAIN_POOL)]))
    print(r"\midrule")
    print("\n".join(rows[len(TRAIN_POOL):]))
    print(r"\bottomrule")
    print(r"\end{tabular}")


if __name__ == "__main__":
    main()
