#!/usr/bin/env python3
"""Render an auditable partial C3 readout while the registered grid is running.

This script deliberately reports only the disclosed Qwen3-4B causal-versus-base
secondary contrast.  It never substitutes that partial slice for the registered
population-prior-minus-causal primary contrast rendered by make_paper_outputs.py.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path

from contrasts import hierarchical_base_contrasts
from make_paper_outputs import (
    BLOCK_LABELS,
    add_overall_rows,
    cell_mean,
    latest_full_ledger,
    report_root,
    validate_full_ledger,
    validate_score_rows,
)
from report import read_scores


ROOT = Path(__file__).resolve().parent
REPO = ROOT.parent.parent
TARGET_MODEL = "qwen3_4b"
TARGET_DISCLOSURE = "disclosed"
TARGET_ARM = "causal_family"


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def endpoint_files(item: dict) -> dict[str, Path] | None:
    root = report_root(item)
    if item["kind"] == "base_evaluation":
        greedy = sorted(root.glob("greedy.scores.jsonl"))
    else:
        greedy = sorted(root.glob("debug_*/eval_results/*.scores.jsonl"))
    stochastic = sorted(root.glob("stochastic_n*.scores.jsonl"))
    if len(greedy) != 1 or len(stochastic) != 1:
        return None
    return {"greedy": greedy[0], "stochastic": stochastic[0]}


def fmt(value: float, digits: int = 3) -> str:
    return f"{value:.{digits}f}"


def interval(item: dict) -> str:
    return (
        f"{item['estimate']:.3f} "
        f"[{item['ci95_low']:.3f},{item['ci95_high']:.3f}]"
    )


def render_overall(rows: list[dict], contrasts: list[dict], seeds: list[int]) -> str:
    index = {
        (item["decode"], item["block"]): item
        for item in contrasts
        if item["model"] == TARGET_MODEL
        and item["disclosure"] == TARGET_DISCLOSURE
    }
    seed_label = ",".join(str(seed) for seed in seeds)
    lines = [
        "% generated by mechanism_family/make_interim_paper_outputs.py -- do not edit",
        r"\begin{tabular}{lrrrrrr}",
        r"\toprule",
        f"Decode & Base MAE & Causal MAE (s{seed_label}) & "
        + r"Base$-$causal [95\% CI] & Base parse & Causal parse & Causal mech. acc. \\",
        r"\midrule",
    ]
    for decode, label in (("greedy", "Greedy"), ("stochastic", "Stochastic $n=5$")):
        common = {
            "model": TARGET_MODEL,
            "disclosure": TARGET_DISCLOSURE,
            "decode": decode,
            "block": "overall",
        }
        base = cell_mean(rows, {**common, "arm": "base"}, "response_mae")
        causal = cell_mean(rows, {**common, "arm": TARGET_ARM}, "response_mae")
        base_parse = cell_mean(rows, {**common, "arm": "base"}, "parsed")
        causal_parse = cell_mean(rows, {**common, "arm": TARGET_ARM}, "parsed")
        mechanism = cell_mean(
            rows, {**common, "arm": TARGET_ARM}, "mechanism_correct"
        )
        effect = index[(decode, "overall")]
        lines.append(
            f"{label} & {fmt(base)} & {fmt(causal)} & {interval(effect)} & "
            f"{fmt(base_parse)} & {fmt(causal_parse)} & {fmt(mechanism)} "
            + r"\\"
        )
    lines.extend([r"\bottomrule", r"\end{tabular}"])
    return "\n".join(lines) + "\n"


def render_blocks(rows: list[dict], contrasts: list[dict], seeds: list[int]) -> str:
    index = {
        (item["decode"], item["block"]): item
        for item in contrasts
        if item["model"] == TARGET_MODEL
        and item["disclosure"] == TARGET_DISCLOSURE
    }
    lines = [
        "% generated by mechanism_family/make_interim_paper_outputs.py -- do not edit",
        r"\begin{tabular}{llrrrrr}",
        r"\toprule",
        r"Decode & Held-out block & Base MAE & Causal MAE & "
        r"Base$-$causal [95\% CI] & Base parse & Causal parse \\",
        r"\midrule",
    ]
    for decode, decode_label in (("greedy", "Greedy"), ("stochastic", "Stoch. $n=5$")):
        for block, block_label in BLOCK_LABELS.items():
            common = {
                "model": TARGET_MODEL,
                "disclosure": TARGET_DISCLOSURE,
                "decode": decode,
                "block": block,
            }
            base = cell_mean(rows, {**common, "arm": "base"}, "response_mae")
            causal = cell_mean(rows, {**common, "arm": TARGET_ARM}, "response_mae")
            base_parse = cell_mean(rows, {**common, "arm": "base"}, "parsed")
            causal_parse = cell_mean(rows, {**common, "arm": TARGET_ARM}, "parsed")
            lines.append(
                f"{decode_label} & {block_label} & {fmt(base)} & {fmt(causal)} & "
                f"{interval(index[(decode, block)])} & {fmt(base_parse)} & "
                f"{fmt(causal_parse)} " + r"\\"
            )
        lines.append(r"\addlinespace")
    lines[-1] = r"\bottomrule"
    lines.append(r"\end{tabular}")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--ledger", type=Path)
    parser.add_argument("--minimum-seeds", type=int, default=2)
    parser.add_argument("--bootstrap-repetitions", type=int, default=5000)
    parser.add_argument("--bootstrap-seed", type=int, default=20260818)
    parser.add_argument(
        "--output",
        type=Path,
        default=ROOT / "reports" / "c3_interim_disclosed_qwen3_4b.json",
    )
    parser.add_argument("--overall-latex", type=Path, action="append", default=[])
    parser.add_argument("--blocks-latex", type=Path, action="append", default=[])
    args = parser.parse_args()

    ledger_path = args.ledger or latest_full_ledger()
    ledger = json.loads(ledger_path.read_text(encoding="utf-8"))
    validate_full_ledger(ledger)

    base_items = [
        item for item in ledger["submissions"]
        if item.get("kind") == "base_evaluation"
        and item.get("model") == TARGET_MODEL
        and item.get("disclosure") == TARGET_DISCLOSURE
    ]
    if len(base_items) != 1:
        raise SystemExit(f"expected one matching base item, found {base_items}")
    base_item = base_items[0]
    base_files = endpoint_files(base_item)
    if base_files is None:
        raise SystemExit("matching untrained base endpoint is incomplete")

    target_items = sorted(
        (
            item for item in ledger["submissions"]
            if item.get("kind") == "training"
            and item.get("model") == TARGET_MODEL
            and item.get("disclosure") == TARGET_DISCLOSURE
            and item.get("arm") == TARGET_ARM
        ),
        key=lambda item: int(item["seed"]),
    )
    completed: list[tuple[dict, dict[str, Path]]] = []
    missing_seeds = []
    for item in target_items:
        files = endpoint_files(item)
        if files is None:
            missing_seeds.append(int(item["seed"]))
        else:
            completed.append((item, files))
    if len(completed) < args.minimum_seeds:
        raise SystemExit(
            f"only {len(completed)} completed causal seeds; "
            f"minimum is {args.minimum_seeds}"
        )

    rows = []
    paths = []
    task_contract = None
    for item, files in [(base_item, base_files), *completed]:
        for decode in ("greedy", "stochastic"):
            path = files[decode]
            score_rows = read_scores([path])
            observed = validate_score_rows(score_rows, item, decode)
            if task_contract is None:
                task_contract = observed
            elif observed != task_contract:
                raise AssertionError(f"{path}: endpoint task universe is not paired")
            rows.extend(score_rows)
            paths.append(path)

    analysis_rows = add_overall_rows(rows)
    contrasts = hierarchical_base_contrasts(
        analysis_rows, args.bootstrap_repetitions, args.bootstrap_seed
    )
    completed_seeds = [int(item["seed"]) for item, _ in completed]
    completed_jobs = [str(item["job_id"]) for item, _ in completed]
    if not any(item["block"] == "overall" for item in contrasts):
        raise AssertionError("interim contrast failed to produce an overall result")

    result = {
        "analysis_status": "interim_registered_secondary_contrast",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "scope": {
            "model": TARGET_MODEL,
            "disclosure": TARGET_DISCLOSURE,
            "arm": TARGET_ARM,
            "comparison": "untrained_base",
            "completed_training_seeds": completed_seeds,
            "completed_job_ids": completed_jobs,
            "missing_training_seeds": missing_seeds,
            "primary_population_prior_minus_causal_contrast_complete": False,
        },
        "ledger": str(ledger_path.relative_to(REPO)),
        "ledger_sha256": sha256(ledger_path),
        "score_files": [str(path.relative_to(REPO)) for path in paths],
        "score_file_sha256": {
            str(path.relative_to(REPO)): sha256(path) for path in paths
        },
        "analysis_code_sha256": {
            str(path.relative_to(REPO)): sha256(path)
            for path in (
                Path(__file__).resolve(),
                ROOT / "make_paper_outputs.py",
                ROOT / "contrasts.py",
                ROOT / "report.py",
            )
        },
        "bootstrap_repetitions": args.bootstrap_repetitions,
        "bootstrap_seed": args.bootstrap_seed,
        "variance_unit": (
            "training seed; paired episode resampling nested within seed; "
            "stochastic draws averaged within episode"
        ),
        "row_draws": len(rows),
        "hierarchical_base_contrasts": contrasts,
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )

    overall = render_overall(analysis_rows, contrasts, completed_seeds)
    blocks = render_blocks(analysis_rows, contrasts, completed_seeds)
    for path in args.overall_latex:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(overall, encoding="utf-8")
    for path in args.blocks_latex:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(blocks, encoding="utf-8")

    print(
        f"rendered interim disclosed Qwen3-4B causal-vs-base result for "
        f"seeds {completed_seeds}; missing {missing_seeds}"
    )
    print(f"result -> {args.output}")


if __name__ == "__main__":
    main()
