"""Render the completed development pilot without selecting models or trials."""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
MODELS = (
    ("qwen2_5_72b_instruct", "Qwen2.5-72B"),
    ("llama3_1_70b_instruct", "Llama-3.1-70B"),
    ("qwen3_32b", "Qwen3-32B"),
)


def render(report: dict) -> str:
    if report.get("material_status") != "authored_development_unvalidated":
        raise ValueError("Expected the unvalidated development cohort")
    if not report.get("run_completion", {}).get("plan_complete"):
        raise ValueError("The prescribed pilot is not complete")
    if report.get("prescribed_models") != [key for key, _ in MODELS]:
        raise ValueError("The prescribed model roster differs")
    if report.get("n_families") != 20:
        raise ValueError("Expected the frozen 20-family pilot")

    def interval(metric: dict, scale: float) -> str:
        if metric["n_missing"] or metric["ci95"] is None:
            raise ValueError("Missing planned measurements or family intervals")
        low, high = metric["ci95"]
        return f"${metric['estimate'] * scale:.1f}$ $[{low * scale:.1f},\\,{high * scale:.1f}]$"

    lines = [
        r"\begin{tabular}{@{}lccc@{}}", r"\toprule",
        r"Model & Correct sign (\%) & Paired reversal (\%) & Broken $|\Delta p|$ (pp) \\",
        r"\midrule",
    ]
    for key, label in MODELS:
        model = report["models"][key]
        coverage = model["coverage"]["totals"]
        if coverage["valid"] != 960 or coverage["expected"] != 960:
            raise ValueError("Expected 960 valid records for every model")
        sign = model["primary"]["direction_correct"]["pooled"]
        pair = model["primary"]["paired_reversal"]["both_directions_correct"]
        broken = model["broken_raw_new_news"]["mean_absolute_pp"]
        if (sign["n_planned"], pair["n_planned"], broken["n_planned"]) != (120, 60, 60):
            raise ValueError("Unexpected planned scoring denominators")
        lines.append(" & ".join([label, interval(sign, 100), interval(pair, 100), interval(broken, 1)]) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}", ""]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--summary", type=Path, default=HERE / "results/development_summary.json")
    parser.add_argument("--output", type=Path, default=HERE.parents[1] / "paper/tables/exp1_context_reversal.tex")
    args = parser.parse_args()
    raw = args.summary.read_bytes()
    table = render(json.loads(raw))
    header = "% Generated by exp1_prospective/context_reversal/make_paper_table.py\n"
    header += "% Completed unvalidated development pilot; source SHA256 " + hashlib.sha256(raw).hexdigest() + "\n"
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(header + table)
    print(args.output)


if __name__ == "__main__":
    main()
