#!/usr/bin/env python3
"""Render the complete Qwen3-4B causal-versus-prior C3 factorial slice.

This is a completed subset of the registered grid: three training seeds, both
training arms, both disclosure conditions, every held-out mechanism block, and
both decoding regimes. The completed Qwen3-4B diagnostic slice includes the
matched structureless arm under both disclosure conditions. It uses the same
estimators as the locked full-grid renderer and never substitutes this one-model
slice for the final model comparisons.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path

from contrasts import (
    hierarchical_base_contrasts,
    hierarchical_disclosure_benefit_contrasts,
    hierarchical_structureless_contrasts,
)
from make_paper_outputs import (
    BLOCK_LABELS,
    MODEL_LABELS,
    add_overall_rows,
    cell_mean,
    latest_full_ledger,
    report_root,
    validate_full_ledger,
    validate_score_rows,
)
from report import hierarchical_arm_contrasts, read_scores


ROOT = Path(__file__).resolve().parent
REPO = ROOT.parent.parent
MODEL = "qwen3_4b"
DISCLOSURES = ("disclosed", "undisclosed")
ARMS = ("causal_family", "population_prior")
SEEDS = (42, 43, 44)
MODELS = ("qwen3_4b", "qwen3_8b", "llama3_1_8b")


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def endpoint_files(item: dict) -> dict[str, Path]:
    root = report_root(item)
    if item["kind"] == "training":
        greedy = sorted(root.glob("debug_*/eval_results/*.scores.jsonl"))
    else:
        greedy = sorted(root.glob("greedy.scores.jsonl"))
    stochastic = sorted(root.glob("stochastic_n*.scores.jsonl"))
    if len(greedy) != 1 or len(stochastic) != 1:
        raise SystemExit(
            f"job {item['job_id']} is incomplete: "
            f"greedy={greedy}, stochastic={stochastic}"
        )
    return {"greedy": greedy[0], "stochastic": stochastic[0]}


def fmt(value: float, digits: int = 3) -> str:
    return f"{value:.{digits}f}"


def interval(item: dict) -> str:
    return (
        f"{item['estimate']:.3f} "
        f"[{item['ci95_low']:.3f},{item['ci95_high']:.3f}]"
    )


def render_overall(rows: list[dict], arm_contrasts: list[dict],
                   disclosure_contrasts: list[dict]) -> str:
    arms = {
        (item["decode"], item["disclosure"]): item
        for item in arm_contrasts
        if item["model"] == MODEL and item["block"] == "overall"
    }
    disclosure = {
        item["decode"]: item
        for item in disclosure_contrasts
        if item["model"] == MODEL and item["block"] == "overall"
    }
    lines = [
        "% generated by mechanism_family/make_completed_q4_paper_outputs.py -- do not edit",
        r"\begin{tabular}{llrrrrr}",
        r"\toprule",
        r"Decode & Structure shown & Prior MAE & Causal MAE & "
        r"Prior$-$causal [95\% CI] & Causal parse & Causal mech. acc. \\",
        r"\midrule",
    ]
    for decode, decode_label in (("greedy", "Greedy"),
                                 ("stochastic", "Stochastic $n=5$")):
        for disclosure_key, disclosure_label in (
            ("disclosed", "Yes"), ("undisclosed", "No")
        ):
            common = {
                "model": MODEL,
                "disclosure": disclosure_key,
                "decode": decode,
                "block": "overall",
            }
            prior = cell_mean(rows, {**common, "arm": "population_prior"},
                              "response_mae")
            causal = cell_mean(rows, {**common, "arm": "causal_family"},
                               "response_mae")
            parse = cell_mean(rows, {**common, "arm": "causal_family"}, "parsed")
            mechanism = cell_mean(
                rows, {**common, "arm": "causal_family"}, "mechanism_correct"
            )
            lines.append(
                f"{decode_label} & {disclosure_label} & {fmt(prior)} & "
                f"{fmt(causal)} & {interval(arms[(decode, disclosure_key)])} & "
                f"{fmt(parse)} & {fmt(mechanism)} " + r"\\"
            )
        interaction = disclosure[decode]
        lines.append(
            r"\multicolumn{2}{r}{Shown$-$hidden causal benefit} & "
            r"\multicolumn{3}{l}{" + interval(interaction) + r"} & & \\"
        )
        lines.append(r"\addlinespace")
    lines[-1] = r"\bottomrule"
    lines.append(r"\end{tabular}")
    return "\n".join(lines) + "\n"


def render_blocks(rows: list[dict], contrasts: list[dict]) -> str:
    index = {
        (item["decode"], item["disclosure"], item["block"]): item
        for item in contrasts if item["model"] == MODEL
    }
    lines = [
        "% generated by mechanism_family/make_completed_q4_paper_outputs.py -- do not edit",
        r"\begin{tabular}{lllrrr}",
        r"\toprule",
        r"Decode & Structure shown & Held-out block & Prior MAE & Causal MAE & "
        r"Prior$-$causal [95\% CI] \\",
        r"\midrule",
    ]
    for decode, decode_label in (("greedy", "Greedy"),
                                 ("stochastic", "Stoch. $n=5$")):
        for disclosure_key, disclosure_label in (
            ("disclosed", "Yes"), ("undisclosed", "No")
        ):
            for block, block_label in BLOCK_LABELS.items():
                common = {
                    "model": MODEL,
                    "disclosure": disclosure_key,
                    "decode": decode,
                    "block": block,
                }
                prior = cell_mean(
                    rows, {**common, "arm": "population_prior"}, "response_mae"
                )
                causal = cell_mean(
                    rows, {**common, "arm": "causal_family"}, "response_mae"
                )
                effect = index[(decode, disclosure_key, block)]
                lines.append(
                    f"{decode_label} & {disclosure_label} & {block_label} & "
                    f"{fmt(prior)} & {fmt(causal)} & {interval(effect)} "
                    + r"\\"
                )
            lines.append(r"\addlinespace")
    lines[-1] = r"\bottomrule"
    lines.append(r"\end{tabular}")
    return "\n".join(lines) + "\n"


def render_diagnostics(rows: list[dict], base_contrasts: list[dict],
                       structureless_contrasts: list[dict]) -> str:
    base = {
        (item["decode"], item["disclosure"]): item
        for item in base_contrasts
        if item["model"] == MODEL and item["block"] == "overall"
    }
    structureless = {
        (item["decode"], item["disclosure"]): item
        for item in structureless_contrasts
        if item["model"] == MODEL and item["block"] == "overall"
    }

    def shown(item: dict | None) -> str:
        return interval(item) if item is not None else "---"

    lines = [
        "% generated by mechanism_family/make_completed_q4_paper_outputs.py -- do not edit",
        r"\begin{tabular}{llrrrrr}",
        r"\toprule",
        r"Decode & Structure shown & Base & Structureless & Causal & "
        r"Base$-$causal [95\% CI] & Structureless$-$causal [95\% CI] \\",
        r"\midrule",
    ]
    for decode, decode_label in (("greedy", "Greedy"),
                                 ("stochastic", "Stochastic $n=5$")):
        for disclosure_key, disclosure_label in (
            ("disclosed", "Yes"), ("undisclosed", "No")
        ):
            common = {
                "model": MODEL,
                "disclosure": disclosure_key,
                "decode": decode,
                "block": "overall",
            }
            base_mae = cell_mean(rows, {**common, "arm": "base"}, "response_mae")
            causal_mae = cell_mean(
                rows, {**common, "arm": "causal_family"}, "response_mae"
            )
            structureless_mae = cell_mean(
                rows, {**common, "arm": "structureless"}, "response_mae"
            )
            structureless_text = (
                fmt(structureless_mae) if structureless_mae == structureless_mae else "---"
            )
            lines.append(
                f"{decode_label} & {disclosure_label} & {fmt(base_mae)} & "
                f"{structureless_text} & {fmt(causal_mae)} & "
                f"{shown(base.get((decode, disclosure_key)))} & "
                f"{shown(structureless.get((decode, disclosure_key)))} " + r"\\"
            )
        lines.append(r"\addlinespace")
    lines[-1] = r"\bottomrule"
    lines.append(r"\end{tabular}")
    return "\n".join(lines) + "\n"


def render_base_roster(rows: list[dict]) -> str:
    lines = [
        "% generated by mechanism_family/make_completed_q4_paper_outputs.py -- do not edit",
        r"\begin{tabular}{lllrrr}",
        r"\toprule",
        r"Decode & Structure shown & Model & Response MAE & Parse & Mech. acc. \\",
        r"\midrule",
    ]
    for decode, decode_label in (("greedy", "Greedy"),
                                 ("stochastic", "Stochastic $n=5$")):
        for disclosure_key, disclosure_label in (
            ("disclosed", "Yes"), ("undisclosed", "No")
        ):
            for model in MODELS:
                common = {
                    "model": model,
                    "disclosure": disclosure_key,
                    "decode": decode,
                    "block": "overall",
                    "arm": "base",
                }
                lines.append(
                    f"{decode_label} & {disclosure_label} & {MODEL_LABELS[model]} & "
                    f"{fmt(cell_mean(rows, common, 'response_mae'))} & "
                    f"{fmt(cell_mean(rows, common, 'parsed'))} & "
                    f"{fmt(cell_mean(rows, common, 'mechanism_correct'))} " + r"\\"
                )
            lines.append(r"\addlinespace")
    lines[-1] = r"\bottomrule"
    lines.append(r"\end{tabular}")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--ledger", type=Path)
    parser.add_argument("--bootstrap-repetitions", type=int, default=5000)
    parser.add_argument("--bootstrap-seed", type=int, default=20260814)
    parser.add_argument(
        "--output",
        type=Path,
        default=ROOT / "reports" / "c3_completed_qwen3_4b_factorial.json",
    )
    parser.add_argument("--overall-latex", type=Path, action="append", default=[])
    parser.add_argument("--blocks-latex", type=Path, action="append", default=[])
    parser.add_argument("--diagnostics-latex", type=Path, action="append", default=[])
    parser.add_argument("--base-roster-latex", type=Path, action="append", default=[])
    args = parser.parse_args()

    ledger_path = (args.ledger or latest_full_ledger()).resolve()
    ledger = json.loads(ledger_path.read_text(encoding="utf-8"))
    validate_full_ledger(ledger)

    expected = {
        (disclosure, arm, seed)
        for disclosure in DISCLOSURES for arm in ARMS for seed in SEEDS
    }
    primary_items = [
        item for item in ledger["submissions"]
        if item.get("kind") == "training" and item.get("model") == MODEL
        and item.get("arm") in ARMS
    ]
    observed = {
        (item.get("disclosure"), item.get("arm"), int(item.get("seed")))
        for item in primary_items
    }
    if len(primary_items) != len(expected) or observed != expected:
        raise SystemExit(
            f"ledger does not contain the exact completed Qwen3-4B slice; "
            f"missing={sorted(expected - observed)}, extra={sorted(observed - expected)}"
        )

    diagnostic_items = [
        item for item in ledger["submissions"]
        if (
            item.get("kind") == "base_evaluation"
            or (
                item.get("kind") == "training"
                and item.get("model") == MODEL
                and item.get("arm") == "structureless"
                and item.get("disclosure") in DISCLOSURES
            )
        )
    ]
    expected_diagnostics = {
        ("training", MODEL, disclosure, "structureless", seed)
        for disclosure in DISCLOSURES for seed in SEEDS
    } | {
        ("base_evaluation", model, disclosure, None, None)
        for model in MODELS for disclosure in DISCLOSURES
    }
    observed_diagnostics = {
        (
            item.get("kind"), item.get("model"), item.get("disclosure"), item.get("arm"),
            int(item["seed"]) if item.get("seed") is not None else None,
        )
        for item in diagnostic_items
    }
    if (len(diagnostic_items) != len(expected_diagnostics)
            or observed_diagnostics != expected_diagnostics):
        raise SystemExit(
            "ledger does not contain the exact completed Qwen3-4B diagnostic slice; "
            f"missing={sorted(expected_diagnostics - observed_diagnostics)}, "
            f"extra={sorted(observed_diagnostics - expected_diagnostics)}"
        )

    paths: list[Path] = []
    rows: list[dict] = []
    reference_tasks = None
    for item in sorted(
        primary_items + diagnostic_items,
        key=lambda value: (
            value["disclosure"], value.get("arm") or "base",
            int(value["seed"]) if value.get("seed") is not None else 0,
        ),
    ):
        files = endpoint_files(item)
        for decode in ("greedy", "stochastic"):
            path = files[decode]
            score_rows = read_scores([path])
            task_contract = validate_score_rows(score_rows, item, decode)
            if reference_tasks is None:
                reference_tasks = task_contract
            elif task_contract != reference_tasks:
                raise AssertionError(f"{path}: endpoint task universe is not paired")
            paths.append(path)
            rows.extend(score_rows)

    analysis_rows = add_overall_rows(rows)
    arm_contrasts = hierarchical_arm_contrasts(
        analysis_rows, args.bootstrap_repetitions, args.bootstrap_seed
    )
    disclosure_contrasts = hierarchical_disclosure_benefit_contrasts(
        analysis_rows, args.bootstrap_repetitions, args.bootstrap_seed
    )
    base_contrasts = hierarchical_base_contrasts(
        analysis_rows, args.bootstrap_repetitions, args.bootstrap_seed
    )
    structureless_contrasts = hierarchical_structureless_contrasts(
        analysis_rows, args.bootstrap_repetitions, args.bootstrap_seed
    )
    expected_contrasts = 2 * 2 * (len(BLOCK_LABELS) + 1)
    if len(arm_contrasts) != expected_contrasts:
        raise AssertionError(
            f"expected {expected_contrasts} arm contrasts, found {len(arm_contrasts)}"
        )
    if len(base_contrasts) != expected_contrasts:
        raise AssertionError(
            f"expected {expected_contrasts} base contrasts, found {len(base_contrasts)}"
        )
    expected_structureless = 2 * len(DISCLOSURES) * (len(BLOCK_LABELS) + 1)
    if len(structureless_contrasts) != expected_structureless:
        raise AssertionError(
            "expected "
            f"{expected_structureless} structureless contrasts, "
            f"found {len(structureless_contrasts)}"
        )

    result = {
        "analysis_status": "completed_registered_qwen3_4b_factorial_slice",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "scope": {
            "model": MODEL,
            "disclosures": list(DISCLOSURES),
            "arms": list(ARMS),
            "training_seeds": list(SEEDS),
            "decodes": ["greedy", "stochastic_n5"],
            "held_out_blocks": list(BLOCK_LABELS),
            "completed_diagnostics": [
                "untrained_three_model_roster_both_disclosures",
                "structureless_both_disclosures_three_seeds",
            ],
            "full_three_model_grid_complete": False,
        },
        "ledger": str(ledger_path.relative_to(REPO)),
        "ledger_sha256": sha256(ledger_path),
        "score_files": [str(path.relative_to(REPO)) for path in paths],
        "score_file_sha256": {
            str(path.relative_to(REPO)): sha256(path) for path in paths
        },
        "analysis_code_sha256": {
            str(path.relative_to(REPO)): sha256(path)
            for path in (
                Path(__file__).resolve(),
                ROOT / "make_paper_outputs.py",
                ROOT / "contrasts.py",
                ROOT / "report.py",
            )
        },
        "bootstrap_repetitions": args.bootstrap_repetitions,
        "bootstrap_seed": args.bootstrap_seed,
        "variance_unit": (
            "training seed; paired episode resampling nested within seed; "
            "stochastic draws averaged within episode"
        ),
        "row_draws": len(rows),
        "analysis_row_draws_including_overall": len(analysis_rows),
        "hierarchical_arm_contrasts": arm_contrasts,
        "hierarchical_base_contrasts": base_contrasts,
        "hierarchical_structureless_contrasts": structureless_contrasts,
        "hierarchical_disclosure_benefit_contrasts": disclosure_contrasts,
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )

    overall = render_overall(analysis_rows, arm_contrasts, disclosure_contrasts)
    blocks = render_blocks(analysis_rows, arm_contrasts)
    diagnostics = render_diagnostics(
        analysis_rows, base_contrasts, structureless_contrasts
    )
    base_roster = render_base_roster(analysis_rows)
    for path in args.overall_latex:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(overall, encoding="utf-8")
    for path in args.blocks_latex:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(blocks, encoding="utf-8")
    for path in args.diagnostics_latex:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(diagnostics, encoding="utf-8")
    for path in args.base_roster_latex:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(base_roster, encoding="utf-8")

    print(
        f"rendered completed Qwen3-4B factorial from {len(paths)} score files "
        f"and {len(rows)} row-draws"
    )
    print(f"result -> {args.output}")


if __name__ == "__main__":
    main()
