#!/usr/bin/env python3
"""Render the ladder calibration table from the scored artifact."""
from __future__ import annotations

import json
from pathlib import Path

from exp1_prospective.context_reversal import run_local as common

HERE = Path(__file__).resolve().parents[1]
REPORT = HERE / 'results/ladder_dev_v1/ladder_calibration.json'
OUT = HERE.parents[1] / 'paper/tables/exp1_ladder_calibration.tex'
NAMES = {'L0_direct': 'Direct statement',
         'L1_permit': 'One step, via permits',
         'L2_office': 'Two steps, via permits and offices',
         'L3_office_distractor': 'Two steps, plus inert relations'}


def main():
    report = json.loads(REPORT.read_text())
    rows = []
    for r in report['rungs']:
        err = '--' if r['posterior_error_mean_pp'] is None else f"{r['posterior_error_mean_pp']:.3f}"
        rows.append(f"{NAMES[r['rung']]} & {r['triples_won']}/{r['triples']} & "
                    f"{r['sign_correct']}/{r['items']} & {r['exact_correct']}/{r['items']} & {err} \\\\")
    table = ('% Generated by exp1_prospective/context_reversal/ladder/make_table.py; do not edit.\n'
             '\\begin{tabular}{lrrrr}\n\\toprule\n'
             'Binding & Triples & Signs & Exact & Error (pp) \\\\\n\\midrule\n'
             + '\n'.join(rows) + '\n\\bottomrule\n\\end{tabular}\n')
    common.atomic_write(OUT, table)
    print(f'wrote {OUT}')


if __name__ == '__main__':
    main()
