#!/usr/bin/env python3
"""Generate the appendix-only Qwen3-8B Coin City probe table and figure."""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt


ROOT = Path(__file__).resolve().parents[1]
RUN = (
    ROOT
    / "exp2_v2"
    / "biased_news"
    / "data"
    / "coin_city_stable_relationship_claude_n250_v4"
    / "mechanistic_probe"
    / "qwen3_8b_toy_v1"
)
RESULTS = RUN / "probe_results.json"
TASK_MANIFEST = RUN / "task_manifest.json"
EXTRACTION_MANIFEST = RUN / "extraction_manifest.json"
LAYERWISE = RUN / "layerwise_results.csv"

EXPECTED_TASKS_SHA256 = (
    "2e0f65d6801b96616fb53b764470960a96b4c08c73483006ca626477de30ccb8"
)
EXPECTED_FEATURES_SHA256 = (
    "e1d99e5913d1b14e00697276298f5c015f56fbb09eb59731bbabad836bb2078b"
)
EXPECTED_MODEL_COMMIT = "b968826d9c46dd6066d109eabc6255188de91218"

TARGETS = (
    ("regime", "Regime (AUC)", "roc_auc", 0.5),
    ("slope", r"Full slope ($R^2$)", "r2", 0.0),
    ("residual_slope", r"Residual slope ($R^2$)", "r2", 0.0),
)
COLORS = {0: "#2C7FB8", 4: "#D55E00"}

plt.rcParams.update(
    {
        "font.family": "sans-serif",
        "font.size": 8,
        "axes.titlesize": 9,
        "axes.labelsize": 8,
        "xtick.labelsize": 7,
        "ytick.labelsize": 7,
        "legend.fontsize": 7,
        "pdf.fonttype": 42,
        "ps.fonttype": 42,
    }
)


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def load_artifacts() -> tuple[dict, dict, dict, list[dict]]:
    """Load the frozen pilot and fail closed on design or artifact drift."""
    results = json.loads(RESULTS.read_text())
    tasks = json.loads(TASK_MANIFEST.read_text())
    extraction = json.loads(EXTRACTION_MANIFEST.read_text())
    with LAYERWISE.open(newline="") as handle:
        layerwise = list(csv.DictReader(handle))

    if results["status"] != "toy_complete":
        raise RuntimeError(f"probe analysis is not complete: {results['status']}")
    if tasks["record_count"] != 384 or tasks["test_per_cell"] != 4:
        raise RuntimeError("toy task dimensions drifted")
    if tasks["tasks_sha256"] != EXPECTED_TASKS_SHA256:
        raise RuntimeError("task manifest hash drifted")
    if _sha256(RUN / "tasks.jsonl") != EXPECTED_TASKS_SHA256:
        raise RuntimeError("tasks.jsonl does not match its frozen hash")
    if results["tasks_sha256"] != EXPECTED_TASKS_SHA256:
        raise RuntimeError("analysis task hash drifted")
    if results["features_sha256"] != EXPECTED_FEATURES_SHA256:
        raise RuntimeError("analysis feature hash drifted")
    if _sha256(RUN / "hidden_states.npz") != EXPECTED_FEATURES_SHA256:
        raise RuntimeError("hidden-state artifact does not match its frozen hash")
    if extraction["model_commit"] != EXPECTED_MODEL_COMMIT:
        raise RuntimeError("Qwen checkpoint commit drifted")
    if extraction["feature_summary"]["feature_shape"] != [384, 37, 4096]:
        raise RuntimeError("hidden-state shape drifted")
    if extraction["behavior_summary"]["parsed_count"] != 96:
        raise RuntimeError("held-out behavior is incomplete")

    primary = [r for r in layerwise if r["representation"] == "last_input_token"]
    expected = {(target, str(k)) for target, *_ in TARGETS for k in (0, 4)}
    observed = {(r["target"], r["c_cases"]) for r in primary}
    if observed != expected:
        raise RuntimeError("primary layerwise conditions drifted")
    for condition in expected:
        layers = sorted(
            int(r["layer"])
            for r in primary
            if (r["target"], r["c_cases"]) == condition
        )
        if layers != list(range(37)):
            raise RuntimeError(f"incomplete layer curve for {condition}")
    return results, tasks, extraction, primary


def _number(value: float) -> str:
    text = f"{value:.3f}"
    if text.startswith("0."):
        return text[1:]
    if text.startswith("-0."):
        return "-" + text[2:]
    return text


def table_body(results: dict) -> str:
    lines = [
        "% Generated by paper/generate_coin_city_mechanistic_probe.py; do not edit."
    ]
    conditions = results["primary"]["conditions"]
    for k in (0, 4):
        for index, (target, label, metric, _) in enumerate(TARGETS):
            condition = conditions[f"k{k}:{target}"]
            selected = condition["selected_test"]
            correct = selected["abc_context"]["probe"]["true_target"][metric]
            absent = selected["abc_no_context"]["probe"]["true_target"][metric]
            wrong = selected["abc_wrong_context"]["probe"]
            wrong_true = wrong["true_target"][metric]
            wrong_cue = wrong.get("cue_target", {}).get(metric)
            permutation = condition["permutation_null_on_correct_context_test"]
            lead = str(k) if index == 0 else ""
            cue_text = "--" if wrong_cue is None else _number(wrong_cue)
            lines.append(
                f"{lead} & {label} & {condition['selected_layer']} & "
                f"{_number(condition['development_cv_score'])} & "
                f"{_number(correct)} & {_number(absent)} & "
                f"{_number(wrong_true)} & {cue_text} & "
                f"{_number(permutation['one_sided_p'])} \\\\" 
            )
        if k == 0:
            lines.append(r"\midrule")
    return "\n".join(lines) + "\n"


def make_figure(results: dict, primary: list[dict], output_base: Path) -> None:
    fig, axes = plt.subplots(1, 3, figsize=(7.05, 2.25), sharex=True)
    conditions = results["primary"]["conditions"]
    panel_titles = (
        "(a) Response regime",
        "(b) Full latent slope",
        "(c) Within-regime residual",
    )

    for ax, (target, _, _, reference), title in zip(axes, TARGETS, panel_titles):
        for k in (0, 4):
            rows = sorted(
                (
                    row
                    for row in primary
                    if row["target"] == target and int(row["c_cases"]) == k
                ),
                key=lambda row: int(row["layer"]),
            )
            x = [int(row["layer"]) for row in rows]
            y = [float(row["cv_score"]) for row in rows]
            ax.plot(x, y, color=COLORS[k], linewidth=1.5, label=f"$k={k}$")
            chosen = conditions[f"k{k}:{target}"]["selected_layer"]
            chosen_y = y[x.index(chosen)]
            ax.scatter(
                [chosen],
                [chosen_y],
                color=COLORS[k],
                marker="*",
                s=42,
                edgecolor="white",
                linewidth=0.5,
                zorder=3,
            )
        ax.axhline(reference, color="#777777", linestyle="--", linewidth=0.8)
        ax.set_title(title, pad=4)
        ax.set_xlabel("Representation layer")
        ax.set_xticks([0, 6, 12, 18, 24, 30, 36])
        ax.grid(axis="y", color="#DDDDDD", linewidth=0.5)
        ax.spines[["top", "right"]].set_visible(False)

    axes[0].set_ylabel("Development CV ROC AUC")
    axes[1].set_ylabel(r"Development CV $R^2$")
    axes[2].set_ylabel(r"Development CV $R^2$")
    axes[0].set_ylim(0.46, 1.04)
    axes[1].set_ylim(-0.06, 0.94)
    axes[2].set_ylim(-0.035, 0.075)
    axes[0].legend(frameon=False, loc="lower right")
    fig.tight_layout(w_pad=1.25)

    output_base.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_base.with_suffix(".pdf"), bbox_inches="tight")
    fig.savefig(output_base.with_suffix(".png"), dpi=300, bbox_inches="tight")
    plt.close(fig)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--table",
        type=Path,
        default=ROOT / "paper" / "tables" / "exp2_qwen3_8b_mechanistic_probe.tex",
    )
    parser.add_argument(
        "--figure-base",
        type=Path,
        default=ROOT / "paper" / "figures" / "exp2_qwen3_8b_mechanistic_probe",
    )
    args = parser.parse_args()

    results, _, _, primary = load_artifacts()
    args.table.parent.mkdir(parents=True, exist_ok=True)
    args.table.write_text(table_body(results))
    make_figure(results, primary, args.figure_base)
    print(args.table)
    print(args.figure_base.with_suffix(".pdf"))
    print(args.figure_base.with_suffix(".png"))


if __name__ == "__main__":
    main()
