#!/usr/bin/env python3
"""Render the completed five-seed shuffled-target control; refuse partial rosters."""
import hashlib
import json
from pathlib import Path

PAPER = Path(__file__).resolve().parent
ROOT = PAPER.parent / 'exp3_training_transfer/overnight_diagnostics_20260921/shuffled_control'
SOURCES = {}


def read(name):
    raw = (ROOT / name).read_bytes()
    SOURCES[name] = hashlib.sha256(raw).hexdigest()
    return json.loads(raw)


def write(name, columns, header, rows):
    text = ['% Generated by paper/generate_exp3_shuffled_control_tables.py; do not edit.',
            r'\begin{tabular}{' + columns + '}', r'\toprule',
            header + r' \\', r'\midrule']
    text += [' & '.join(row) + r' \\' for row in rows]
    text += [r'\bottomrule', r'\end{tabular}', '']
    (PAPER / 'tables' / name).write_text('\n'.join(text))


def rows_for(contrasts, metric):
    rows = []
    for disclosure in ('disclosed', 'undisclosed'):
        for decode in ('greedy', 'stochastic'):
            c, = [x for x in contrasts if (x['scope'], x['metric'], x['disclosure'], x['decode'])
                  == ('overall', metric, disclosure, decode)]
            assert c['complete_five_seed_roster'] and c['training_seeds'] == 5
            assert c['tasks_per_seed'] == 720
            t_lo, t_hi = c['student_t_95ci']
            h_lo, h_hi = c['hierarchical_seed_trajectory_95ci']
            rows.append([disclosure.title(), decode.title(), f"{c['effect']:+.3f}",
                         f'[{t_lo:+.3f}, {t_hi:+.3f}]', f'[{h_lo:+.3f}, {h_hi:+.3f}]',
                         f"{c['wild_cluster_webb_p_two_sided']:.3f}",
                         f"{c['sign_test']['positive']}/{c['sign_test']['seeds']}"])
    return rows


def main():
    results = read('results.json')
    status = read('finalization_status.json')
    assert results['complete'] and not results['incomplete_cells'], 'partial roster'
    assert status['complete'] and status['analysis_exit_code'] == 0, 'finalization incomplete'
    assert len(results['cells']) == 40
    assert results['comparator'] == 'same_hardware'
    assert results['primary'] == 'stochastic5 shuffled minus matched response MAE'
    contrasts = results['contrasts']

    header = (r'Disclosure & Decode & Shuffled$-$matched & 95\% Student-$t$ & '
              r'95\% hierarchical & Webb $p$ & Seeds $>0$')
    write('exp3_shuffled_control.tex', 'llrrrrr', header, rows_for(contrasts, 'response_mae'))
    write('exp3_shuffled_control_level.tex', 'llrrrrr', header, rows_for(contrasts, 'level_mae'))

    (PAPER / 'tables/exp3_shuffled_control_sources.json').write_text(json.dumps({
        'generator': 'paper/generate_exp3_shuffled_control_tables.py',
        'artifact_root': str(ROOT.relative_to(PAPER.parent)),
        'source_sha256': SOURCES,
        'freeze_sha256': results['freeze_sha256'],
        'analysis_code_sha256': results['analysis_code_sha256'],
        'primary_estimand': results['primary'],
        'finished_at': status['finished_at'],
        'scope': 'Completed five-seed distribution-matched shuffled-target control, same-hardware comparator.',
    }, indent=2) + '\n')


if __name__ == '__main__':
    main()
