#!/usr/bin/env python3
"""Render the registered Coin City robustness analyses as appendix tables."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EXP2 = ROOT / "exp2_v2" / "biased_news"
POPULATION = (
    EXP2
    / "data"
    / "coin_city_population_075_040_sd010_v1"
    / "analysis"
    / "population_robustness_results_v1.json"
)
REPEAT = (
    EXP2
    / "data"
    / "coin_city_stable_relationship_claude_n250_v4"
    / "analysis"
    / "gpt56_k0_repeat_v1.json"
)
TABLES = ROOT / "paper" / "tables"
MODEL_ORDER = (
    "Qwen3-4B-Instruct-2507",
    "Qwen3-8B",
    "Qwen3-14B",
    "Qwen3-32B",
    "Qwen2.5-7B-Instruct",
    "Qwen2.5-14B-Instruct",
    "Qwen2.5-32B-Instruct",
    "Qwen2.5-72B-Instruct",
    "Llama-3.1-8B-Instruct",
    "Llama-3.1-70B-Instruct",
)
DISPLAY = {
    "Qwen3-4B-Instruct-2507": "Qwen3-4B",
    "Qwen3-8B": "Qwen3-8B",
    "Qwen3-14B": "Qwen3-14B",
    "Qwen3-32B": "Qwen3-32B",
    "Qwen2.5-7B-Instruct": "Qwen2.5-7B",
    "Qwen2.5-14B-Instruct": "Qwen2.5-14B",
    "Qwen2.5-32B-Instruct": "Qwen2.5-32B",
    "Qwen2.5-72B-Instruct": "Qwen2.5-72B",
    "Llama-3.1-8B-Instruct": "Llama-3.1-8B",
    "Llama-3.1-70B-Instruct": "Llama-3.1-70B",
}
ARM_DISPLAY = {
    "abc_no_context": "No C context",
    "abc_context": "Semantic context",
    "abc_symbol_context": "Arbitrary symbol",
}


def number(value: float, *, signed: bool = False) -> str:
    if round(value, 3) == 0:
        value = 0.0
    text = f"{value:+.3f}" if signed else f"{value:.3f}"
    return text.replace("+0.", "+.").replace("-0.", "-.").replace("0.", ".")


def interval(record: dict, *, key: str, signed: bool = True) -> str:
    low, high = record["ci_95"]
    text = (
        f"${number(record[key], signed=signed)}$ "
        f"$[{number(low, signed=False)},{number(high, signed=False)}]$"
    )
    if low > 0 or high < 0:
        return rf"\textbf{{{text}}}"
    return text


def render_population(data: dict) -> str:
    if (
        data.get("protocol_version") != "coin_city_robustness_v1"
        or not data.get("status") == "complete"
    ):
        raise ValueError(
            "population robustness artifact is not complete and registered"
        )
    rows = []
    for model in MODEL_ORDER:
        comparison = data["k0_point_comparison"][model]
        old = comparison["original_population"]["symbol_minus_no_context_rho"]
        new = comparison["harder_population"]["symbol_minus_no_context_rho"]
        accuracy = comparison["harder_population"]["symbol_regime_accuracy"]
        mae = data["models"][model]["curves"]["0"]["paired_forecast_mae"][
            "symbol_minus_no_context"
        ]
        rows.append(
            " & ".join(
                (
                    DISPLAY[model],
                    str(data["models"][model]["curves"]["0"]["n"]),
                    interval(old, key="difference"),
                    interval(new, key="difference"),
                    number(accuracy),
                    interval(mae, key="mean"),
                )
            )
            + r" \\"
        )
    return "\n".join(
        (
            "% Generated by paper/generate_coin_city_robustness_tables.py; do not edit.",
            r"\begin{tabular}{lrcccc}",
            r"\toprule",
            r"Model & $n$ & Original $\Delta\rho$ [95\% CI] & Harder $\Delta\rho$ [95\% CI] & Symbol acc. & Harder $\Delta$MAE [95\% CI] \\",
            r"\midrule",
            *rows,
            r"\bottomrule",
            r"\end{tabular}",
            "",
        )
    )


def render_repeat(data: dict) -> str:
    if (
        data.get("protocol_version") != "coin_city_robustness_v1"
        or not data.get("status") == "complete"
    ):
        raise ValueError("GPT repeat artifact is not complete and registered")
    rows = []
    for arm in ("abc_no_context", "abc_context", "abc_symbol_context"):
        record = data["per_arm"][arm]
        rows.append(
            " & ".join(
                (
                    ARM_DISPLAY[arm],
                    number(record["original"]["forecast_mae"]),
                    number(record["repeat"]["forecast_mae"]),
                    interval(record["repeat_minus_original_forecast_mae"], key="mean"),
                    number(record["original"]["rho"]),
                    number(record["repeat"]["rho"]),
                    interval(record["repeat_minus_original_rho"], key="difference"),
                    number(record["prediction_absolute_delta"]["mean"]),
                )
            )
            + r" \\"
        )
    return "\n".join(
        (
            "% Generated by paper/generate_coin_city_robustness_tables.py; do not edit.",
            r"\begin{tabular}{lccccccc}",
            r"\toprule",
            r"& \multicolumn{3}{c}{Forecast MAE} & \multicolumn{3}{c}{$\rho(\hat g,g_C)$} & Mean $|\Delta\hat y|$ \\",
            r"\cmidrule(lr){2-4}\cmidrule(lr){5-7}",
            r"Arm & Original & Repeat & Repeat $-$ original [95\% CI] & Original & Repeat & Repeat $-$ original [95\% CI] & \\",
            r"\midrule",
            *rows,
            r"\bottomrule",
            r"\end{tabular}",
            "",
        )
    )


def main() -> None:
    population = json.loads(POPULATION.read_text(encoding="utf-8"))
    repeat = json.loads(REPEAT.read_text(encoding="utf-8"))
    TABLES.mkdir(parents=True, exist_ok=True)
    (TABLES / "exp2_generator_population_robustness.tex").write_text(
        render_population(population), encoding="utf-8"
    )
    (TABLES / "exp2_gpt56_repeat.tex").write_text(
        render_repeat(repeat), encoding="utf-8"
    )
    print("Wrote Coin City robustness appendix tables")


if __name__ == "__main__":
    main()
