#!/usr/bin/env python3
"""Generate the Coin City reference-selection appendix tables.

Reads the frozen authority written by
exp2_v2/biased_news/analysis/analyze_coin_city_reference_selection.py and emits
two table bodies: the four-arm primary-deployment table at k=0 and the
arbitrary-symbol table across the released open-weight and hosted roster.
"""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RESULTS = (
    ROOT
    / "exp2_v2"
    / "biased_news"
    / "data"
    / "coin_city_stable_relationship_claude_n250_v4"
    / "analysis"
    / "reference_selection_results.json"
)
PRIMARY_TABLE = ROOT / "paper" / "tables" / "exp2_reference_selection.tex"
SYMBOL_TABLE = ROOT / "paper" / "tables" / "exp2_reference_selection_symbol.tex"

PRIMARY_ORDER = (
    ("claude-opus-4-8", "Claude Opus~4.8"),
    ("gpt-5.6-sol", "GPT-5.6"),
    ("DeepSeek-V4-Pro", "DeepSeek V4-Pro"),
    ("FW-Kimi-K3", "Kimi K3"),
    ("gemini-3.6-flash", "Gemini 3.6 Flash"),
    ("claude-opus-5", "Claude Opus~5"),
)
SYMBOL_ORDER = (
    ("Qwen3-4B-Instruct-2507", "Qwen3-4B"),
    ("Qwen2.5-7B-Instruct", "Qwen2.5-7B"),
    ("Qwen3-8B", "Qwen3-8B"),
    ("Qwen2.5-14B-Instruct", "Qwen2.5-14B"),
    ("Qwen3-14B", "Qwen3-14B"),
    ("Qwen3-32B", "Qwen3-32B"),
    ("Qwen2.5-32B-Instruct", "Qwen2.5-32B"),
    ("Qwen2.5-72B-Instruct", "Qwen2.5-72B"),
    ("Llama-3.1-8B-Instruct", "Llama~3.1 8B"),
    ("Llama-3.1-70B-Instruct", "Llama~3.1 70B"),
    ("DeepSeek-V4-Pro", "DeepSeek V4-Pro"),
    ("FW-Kimi-K3", "Kimi K3"),
    ("claude-opus-4-8", "Claude Opus~4.8"),
    ("claude-opus-5", "Claude Opus~5"),
    ("gpt-5.6-sol", "GPT-5.6 Sol"),
)
ARM_COLUMNS = (
    ("baseline", "regime_matched_reference", "regime_mismatched_reference"),
    ("abc_no_context", "regime_matched_reference", "regime_mismatched_reference"),
    ("abc_context", "cue_reference", "other_reference"),
    ("abc_wrong_context", "cue_reference", "other_reference"),
)


def _dot(value: float) -> str:
    text = f"{value:.2f}"
    for prefix, replacement in (("0.", "."), ("-0.", "-.")):
        if text.startswith(prefix):
            return replacement + text[len(prefix):]
    return text


def _cell(metric: dict, *, bold_if_excludes_zero: bool = True) -> str:
    value = metric.get("partial_r")
    if value is None:
        return "---"
    low, high = metric["ci_95"]
    text = f"${_dot(value)}$"
    if bold_if_excludes_zero and low is not None and low * high > 0:
        text = f"\\textbf{{{text}}}"
    return text


def primary_rows(results: dict) -> str:
    lines = []
    for model, label in PRIMARY_ORDER:
        arms = results["primary"][model]["arms"]
        cells = []
        for arm, named_key, other_key in ARM_COLUMNS:
            cell = arms[arm]["0"]
            cells.append(_cell(cell[named_key]))
            cells.append(_cell(cell[other_key], bold_if_excludes_zero=False))
        lines.append(f"{label} & " + " & ".join(cells) + r" \\")
    return "\n".join(lines)


def symbol_rows(results: dict) -> str:
    lines = []
    for model, label in SYMBOL_ORDER:
        entry = results["symbol"].get(model)
        if entry is None:
            continue
        pooled = entry["arms"]["abc_no_context"]["0"]
        symbol = entry["arms"]["abc_symbol_context"]["0"]
        lines.append(
            f"{label} & {symbol['n']} & "
            + _cell(pooled["regime_matched_reference"], bold_if_excludes_zero=False)
            + " & "
            + _cell(pooled["regime_mismatched_reference"], bold_if_excludes_zero=False)
            + " & "
            + _cell(symbol["cue_reference"])
            + " & "
            + _cell(symbol["other_reference"], bold_if_excludes_zero=False)
            + r" \\"
        )
    return "\n".join(lines)


HEADER = (
    "% Generated by paper/generate_coin_city_reference_selection_tables.py "
    "from analysis/reference_selection_results.json; do not edit.\n"
)

PRIMARY_PREAMBLE = r"""\begin{tabular}{l cc cc cc cc}
\toprule
& \multicolumn{2}{c}{Target only} & \multicolumn{2}{c}{ABC, no label}
& \multicolumn{2}{c}{ABC + correct} & \multicolumn{2}{c}{ABC + inverted} \\
\cmidrule(lr){2-3}\cmidrule(lr){4-5}\cmidrule(lr){6-7}\cmidrule(lr){8-9}
Model & Named & Other & Named & Other & Named & Other & Named & Other \\
\midrule"""

SYMBOL_PREAMBLE = r"""\begin{tabular}{l r cc cc}
\toprule
& & \multicolumn{2}{c}{ABC, no label} & \multicolumn{2}{c}{ABC + symbol} \\
\cmidrule(lr){3-4}\cmidrule(lr){5-6}
Model & $n$ & Named & Other & Named & Other \\
\midrule"""

CLOSING = "\n\\bottomrule\n\\end{tabular}\n"


def main() -> None:
    results = json.loads(RESULTS.read_text())
    PRIMARY_TABLE.parent.mkdir(parents=True, exist_ok=True)
    PRIMARY_TABLE.write_text(
        HEADER + PRIMARY_PREAMBLE + "\n" + primary_rows(results) + CLOSING
    )
    SYMBOL_TABLE.write_text(
        HEADER + SYMBOL_PREAMBLE + "\n" + symbol_rows(results) + CLOSING
    )
    print(f"Wrote {PRIMARY_TABLE}")
    print(f"Wrote {SYMBOL_TABLE}")


if __name__ == "__main__":
    main()
