#!/usr/bin/env python3
"""Generate the Coin City arbitrary-symbol appendix tables from final results."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RESULTS = (
    ROOT
    / "exp2_v2"
    / "biased_news"
    / "data"
    / "coin_city_stable_relationship_claude_n250_v4"
    / "analysis"
    / "symbol_context_model_comparison_20260824.json"
)
K0_TABLE = ROOT / "paper" / "tables" / "exp2_symbol_context_results.tex"
SCALING_TABLE = (
    ROOT / "paper" / "tables" / "exp2_symbol_context_scaling.tex"
)

MODEL_ORDER = (
    "Qwen3-4B-Instruct-2507",
    "Qwen2.5-7B-Instruct",
    "Qwen3-8B",
    "Qwen2.5-14B-Instruct",
    "Qwen3-14B",
    "Qwen3-32B",
    "Qwen2.5-32B-Instruct",
    "Qwen2.5-72B-Instruct",
    "Llama-3.1-8B-Instruct",
    "Llama-3.1-70B-Instruct",
    "DeepSeek-V4-Pro",
    "FW-Kimi-K3",
    "claude-opus-4-8",
    "claude-opus-5",
    "gpt-5.6-sol",
)
DISPLAY = {
    "Qwen3-4B-Instruct-2507": "Qwen3-4B",
    "Qwen2.5-7B-Instruct": "Qwen2.5-7B",
    "Qwen3-8B": "Qwen3-8B",
    "Qwen2.5-14B-Instruct": "Qwen2.5-14B",
    "Qwen3-14B": "Qwen3-14B",
    "Qwen3-32B": "Qwen3-32B",
    "Qwen2.5-32B-Instruct": "Qwen2.5-32B",
    "Qwen2.5-72B-Instruct": "Qwen2.5-72B",
    "Llama-3.1-8B-Instruct": "Llama-3.1-8B",
    "Llama-3.1-70B-Instruct": "Llama-3.1-70B",
    "DeepSeek-V4-Pro": "DeepSeek V4-Pro",
    "FW-Kimi-K3": "Kimi K3",
    "claude-opus-4-8": "Claude Opus~4.8",
    "claude-opus-5": "Claude Opus~5",
    "gpt-5.6-sol": "GPT-5.6",
}


def _number(value: float, *, signed: bool = False) -> str:
    text = f"{value:+.3f}" if signed else f"{value:.3f}"
    return text.replace("+0.", "+.").replace("-0.", "-.").replace("0.", ".")


def _interval(metric: dict, key: str) -> str:
    low, high = metric["ci_95"]
    return (
        f"${_number(metric[key], signed=True)}$ "
        f"$[{_number(low)},{_number(high)}]$"
    )


def _validate(results: dict) -> None:
    if results.get("status") != "complete_posthoc_comparison":
        raise RuntimeError(f"Unexpected result status: {results.get('status')!r}")
    if results.get("not_for_paper") is not False:
        raise RuntimeError("The final comparison has not been released for paper use")
    if set(results["models"]) != set(MODEL_ORDER):
        raise RuntimeError("Unexpected model roster")
    for model in MODEL_ORDER:
        model_result = results["models"][model]
        if any(count != 1_250 for count in model_result["record_counts"].values()):
            raise RuntimeError(f"Incomplete response files for {model}")
        if not 1 <= model_result["curves"]["0"]["n"] <= 250:
            raise RuntimeError(f"Invalid k=0 complete-case count for {model}")


def _k0_table(results: dict) -> str:
    header = (
        "% Generated by paper/generate_coin_city_symbol_context_tables.py from the "
        "final 2026-08-24 comparison artifact; do not edit."
    )
    forecast = [
        header,
        "\\textit{Panel A: Forecast accuracy}\\par\\vspace{-2pt}",
        "\\resizebox{0.82\\linewidth}{!}{%",
        "\\begin{tabular}{l r rrr c}",
        "\\toprule",
        "Model & $n$ & No context & Semantic & Symbol & $\\Delta$MAE [95\\% CI] \\\\",
        "\\midrule",
    ]
    discrimination = [
        "\\textit{Panel B: Response-regime discrimination}\\par\\vspace{-2pt}",
        "\\resizebox{\\linewidth}{!}{%",
        "\\begin{tabular}{l r rr c rr c}",
        "\\toprule",
        "& & \\multicolumn{2}{c}{$\\rho(\\hat g,g_C)$} & "
        "& \\multicolumn{2}{c}{Regime accuracy} & \\\\",
        "\\cmidrule(lr){3-4}\\cmidrule(lr){6-7}",
        "Model & $n$ & No context & Symbol & $\\Delta\\rho$ [95\\% CI] & "
        "No context & Symbol & $\\Delta$Acc. [95\\% CI] \\\\",
        "\\midrule",
    ]
    for index, model in enumerate(MODEL_ORDER):
        if index == 8:
            forecast.append("\\midrule")
            discrimination.append("\\midrule")
        curve = results["models"][model]["curves"]["0"]
        arms = curve["arms"]
        forecast.append(
            f"{DISPLAY[model]} & "
            f"{curve['n']} & "
            f"{_number(arms['abc_no_context']['forecast_mae'])} & "
            f"{_number(arms['abc_context']['forecast_mae'])} & "
            f"{_number(arms['abc_symbol_context']['forecast_mae'])} & "
            f"{_interval(curve['paired_forecast_mae']['symbol_minus_no_context'], 'mean')} \\\\"
        )
        discrimination.append(
            f"{DISPLAY[model]} & "
            f"{curve['n']} & "
            f"{_number(arms['abc_no_context']['rho'])} & "
            f"{_number(arms['abc_symbol_context']['rho'])} & "
            f"{_interval(curve['paired_discrimination']['symbol_minus_no_context_rho'], 'difference')} & "
            f"{_number(arms['abc_no_context']['regime_accuracy'])} & "
            f"{_number(arms['abc_symbol_context']['regime_accuracy'])} & "
            f"{_interval(curve['paired_discrimination']['symbol_minus_no_context_regime_accuracy'], 'difference')} \\\\"
        )
    forecast.extend(("\\bottomrule", "\\end{tabular}}"))
    discrimination.extend(("\\bottomrule", "\\end{tabular}}"))
    return "\n".join(forecast + ["\\par\\vspace{4pt}"] + discrimination) + "\n"


def _scaling_table(results: dict) -> str:
    lines = [
        "% Generated by paper/generate_coin_city_symbol_context_tables.py from the "
        "final 2026-08-24 comparison artifact; do not edit.",
        "\\begin{tabular}{l rr ccc}",
        "\\toprule",
        "Model & $k$ & $n$ & $\\Delta$MAE [95\\% CI] & "
        "$\\Delta\\rho$ [95\\% CI] & $\\Delta$Acc. [95\\% CI] \\\\",
        "\\midrule",
    ]
    scaling_models = (
        "Qwen2.5-32B-Instruct",
        "Qwen2.5-72B-Instruct",
        "Llama-3.1-8B-Instruct",
        "Llama-3.1-70B-Instruct",
    )
    for model_index, model in enumerate(scaling_models):
        if model_index:
            lines.append("\\midrule")
        for k in range(5):
            curve = results["models"][model]["curves"][str(k)]
            label = DISPLAY[model] if k == 0 else ""
            lines.append(
                f"{label} & {k} & {curve['n']} & "
                f"{_interval(curve['paired_forecast_mae']['symbol_minus_no_context'], 'mean')} & "
                f"{_interval(curve['paired_discrimination']['symbol_minus_no_context_rho'], 'difference')} & "
                f"{_interval(curve['paired_discrimination']['symbol_minus_no_context_regime_accuracy'], 'difference')} \\\\"
            )
    lines.extend(("\\bottomrule", "\\end{tabular}"))
    return "\n".join(lines) + "\n"


def main() -> None:
    results = json.loads(RESULTS.read_text(encoding="utf-8"))
    _validate(results)
    K0_TABLE.write_text(_k0_table(results), encoding="utf-8")
    SCALING_TABLE.write_text(_scaling_table(results), encoding="utf-8")
    print(f"Wrote {K0_TABLE}")
    print(f"Wrote {SCALING_TABLE}")


if __name__ == "__main__":
    main()
