#!/usr/bin/env python3
"""Emit the Coin City causal activation-patching table body.

Reads the powered 88-episode relational run and fails closed if it is incomplete,
if its stability gate did not pass, or if it is not the run the paper cites.
"""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RUN_DIR = (
    ROOT
    / "exp2_v2"
    / "biased_news"
    / "data"
    / "coin_city_stable_relationship_claude_n250_v4"
    / "mechanistic_probe"
    / "qwen3_14b_symbol_relational_v2"
)
PILOT_DIR = RUN_DIR.with_name("qwen3_14b_symbol_relational_v1")
OUTPUT = ROOT / "paper" / "tables" / "exp2_causal_patch.tex"
EXPECTED_STUDY = "qwen3_14b_symbol_relational_v2"
EXPECTED_SEALED_EPISODES = 88
CONDITIONS = (
    ("cross_selected_window", "Selected window"),
    ("cross_embedding_only", "Embedding only"),
    ("cross_all_layers", "All layers"),
)


def _dot(value: float, places: int = 3) -> str:
    text = f"{value:.{places}f}"
    for prefix, replacement in (("0.", "."), ("-0.", "-.")):
        if text.startswith(prefix):
            return replacement + text[len(prefix):]
    return text


def _p(value: float) -> str:
    if value < 1e-4:
        return "$<$.0001"
    return f"${_dot(value, 4)}$"


def load(directory: Path, study: str) -> dict:
    results = json.loads((directory / "relational_probe_results.json").read_text())
    if results.get("status") != "complete":
        raise SystemExit(f"{directory.name}: status is {results.get('status')!r}")
    if results.get("study") != study:
        raise SystemExit(f"{directory.name}: study is {results.get('study')!r}")
    return results


def rows() -> str:
    powered = load(RUN_DIR, EXPECTED_STUDY)
    pilot = load(PILOT_DIR, "qwen3_14b_symbol_relational_v1")
    manifest = json.loads((RUN_DIR / "task_manifest.json").read_text())
    sealed = manifest["episode_counts"]["test"]
    if sealed != EXPECTED_SEALED_EPISODES:
        raise SystemExit(f"sealed test is {sealed}, expected {EXPECTED_SEALED_EPISODES}")
    if not powered["stability_gate"]["passed"]:
        raise SystemExit("the powered run did not pass its frozen stability gate")

    lines = []
    for index, (key, label) in enumerate(CONDITIONS):
        if index:
            lines.append(r"\midrule")
        for depth in ("k0", "k4"):
            old = pilot["patching"]["conditions"][key][depth]
            new = powered["patching"]["conditions"][key][depth]
            lead = label if depth == "k0" else ""
            lines.append(
                f"{lead} & ${depth[0]}{{=}}{depth[1:]}$ & "
                f"${_dot(old['mean'])}$ & ${_dot(old['one_sided_p'], 2)}$ & {old['n']} & "
                f"${_dot(new['mean'])}$ & {_p(new['one_sided_p'])} & {new['n']} & "
                f"$[{_dot(new['null_q025'])},{_dot(new['null_q975'])}]$" + r" \\"
            )
    return "\n".join(lines)


def main() -> None:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    preamble = (
        "\\begin{tabular}{l c rrr rrr c}\n"
        "\\toprule\n"
        "& & \\multicolumn{3}{c}{16 sealed, window 33--35}"
        " & \\multicolumn{3}{c}{88 sealed, window 19--21} & \\\\\n"
        "\\cmidrule(lr){3-5}\\cmidrule(lr){6-8}\n"
        "Patch site & $k$ & Shift & $p$ & $n$ & Shift & $p$ & $n$ & Null 95\\% \\\\\n"
        "\\midrule"
    )
    OUTPUT.write_text(
        "% Generated by paper/generate_coin_city_causal_patch_table.py; do not edit.\n"
        + preamble
        + "\n"
        + rows()
        + "\n\\bottomrule\n\\end{tabular}\n"
    )
    print(f"Wrote {OUTPUT}")


if __name__ == "__main__":
    main()
