#!/usr/bin/env python3
"""Render completed exploratory Exp. 3 diagnostics; never ingest pending controls."""
import csv
import hashlib
import json
from pathlib import Path
from statistics import mean

PAPER = Path(__file__).resolve().parent
ROOT = PAPER.parent / 'exp3_training_transfer/overnight_diagnostics_20260921'
CELLS = [(d, l) for d in ('coin_city', 'coin_harbor') for l in ('semantic', 'arbitrary')]
SOURCES = {}


def read(name):
    raw = (ROOT / name).read_bytes()
    SOURCES[name] = hashlib.sha256(raw).hexdigest()
    return json.loads(raw)


def write(name, columns, header, rows):
    text = ['% Generated by paper/generate_exp3_diagnostic_tables.py; do not edit.',
            r'\begin{tabular}{' + columns + '}', r'\toprule',
            header + r' \\', r'\midrule']
    text += [' & '.join(row) + r' \\' for row in rows]
    text += [r'\bottomrule', r'\end{tabular}', '']
    (PAPER / 'tables' / name).write_text('\n'.join(text))


def main():
    comparison = read('learnability/component_comparison.json')
    receipt = read('structure/completion_receipt.json')
    evidence = read('evidence_use/analysis_ext/summary.json')
    audit = read('structure/baseline_omission_audit.json')
    assert not comparison['pending'] and len(receipt['models']) == 8
    assert evidence['complete'] and evidence['gain_complete']
    summaries = comparison['summaries']
    assert all(s['n'] == 768 and len(s['cells']) == 16 for s in summaries.values())
    models = [('Base 8B', 'Base'), ('Matched RL seed42', 'RL'),
              ('SFT forecast_lr1e6 seed42', r'SFT $10^{-6}$'),
              ('SFT forecast_lr2e5 seed42', r'SFT $2\!\times\!10^{-5}$')]
    rows = []
    for domain, labels in CELLS:
        for key, label in models:
            c, = [x for x in summaries[key]['cells'] if (x['domain'], x['label_kind'], x['interface']) == (domain, labels, 'original')]
            assert c['n_pairs'] == 24 and c['n'] == 48 and c['parse_rate'] == 1
            lo, hi = c['cue_change_calibration_ci95']
            rows.append([domain.removeprefix('coin_').title(), labels, label,
                         f"{100*c['accuracy']:.1f}", f"{c['response_mae']:.3f}",
                         f"{c['cue_change_calibration']:.3f}", f'[{lo:.3f}, {hi:.3f}]'])
    write('exp3_learnability.tex', 'lllrrrr',
          r'Domain & Labels & Recipe & Structure (\%) & Resp. MAE & $\alpha$ & 95\% interval', rows)
    raw = (ROOT / 'structure/summary.csv').read_bytes()
    SOURCES['structure/summary.csv'] = hashlib.sha256(raw).hexdigest()
    data = list(csv.DictReader(raw.decode().splitlines()))
    groups = [('8B base', ['qwen3_8b_base']),
              ('8B matched RL', [f'qwen3_8b_causal_s{s}' for s in (42,43,44)]),
              ('8B prior RL', [f'qwen3_8b_population_prior_s{s}' for s in (42,43,44)]),
              ('32B base', ['qwen3_32b_base'])]
    rows = []
    for domain, labels in CELLS:
        for label, keys in groups:
            values = []
            for interface in ('selection_only', 'original', 'oracle_both_patterns', 'oracle_selected_pattern'):
                subset = [r for r in data if r['model_key'] in keys and (r['domain'],r['label_kind'],r['interface']) == (domain,labels,interface)]
                assert len(subset) == len(keys)
                assert all(int(r['n']) == 48 and float(r['parse_rate']) == 1 for r in subset)
                metric = 'accuracy' if interface == 'selection_only' else 'response_mae'
                value = mean(float(r[metric]) for r in subset)
                values.append(f'{100*value:.0f}' if interface == 'selection_only' else f'{value:.3f}')
            rows.append([domain.removeprefix('coin_').title(), labels, label] + values)
    write('exp3_components.tex', 'lllrrrr',
          r'Domain & Labels & Model & Name (\%) & Original & Both & Selected', rows)
    rows = []
    for domain, labels in CELLS:
        cells = {r['interface']: r for r in audit['cells'] if (r['model_key'], r['domain'], r['label_kind']) == ('qwen3_32b_base',domain,labels)}
        selected = cells['oracle_selected_pattern']
        rows.append([domain.removeprefix('coin_').title(), labels] +
                    [f"{cells[i]['raw_response_mae']:.3f}" for i in ('original','oracle_both_patterns','oracle_selected_pattern')] +
                    [f"{100*selected['relative_vector_exact_01']:.1f}", f"{100*selected['both_zero_shocks_near_zero']:.1f}"])
    write('exp3_baseline_audit.tex','llrrrrr',
          r'Domain & Labels & Original & Both & Selected & Exact (\%) & Omit rest (\%)',rows)
    rows = []
    for disclosure in ('disclosed','undisclosed'):
        for group, label in [('train','Seen'),('test','Held out')]:
            vals = []
            slopes = []
            for arm in ('base','causal_family','shuffled_target'):
                subset = [r for r in evidence['gain_summary'] if (r['disclosure'],r['group'],r['arm']) == (disclosure,group,arm)]
                assert len(subset) == (1 if arm == 'base' else 5)
                vals.append(f"{mean(r['change_mae'] for r in subset):.3f}")
                slopes.append(mean(r['tracking_slope'] for r in subset))
            contrast, = [r for r in evidence['paired_contrasts'] if (r['disclosure'],r['group'],r['contrast']) == (disclosure,group,'shuffled_target_minus_causal_family_change_mae')]
            assert contrast['training_seeds'] == [42,43,44,45,46]
            lo, hi = contrast['ci95']
            rows.append([disclosure.title(),label] + vals +
                        [f"{subset[0]['no_change_mae']:.3f}",
                         f'{slopes[1]:.3f}', f'{slopes[2]:.3f}',
                         f"{contrast['estimate']:+.3f}",f'[{lo:+.3f}, {hi:+.3f}]'])
    write('exp3_gain_evidence.tex','llrrrrrrrr',
          r'Disclosure & Mechanisms & Base & Matched & Shuffled & No change & '
          r'Slope M & Slope S & Shuffled$-$matched & 95\% interval', rows)
    # Seed replication of the successful 2e-5 recipe (seeds 43-45 extend seed 42).
    lroot = ROOT / 'learnability'
    rows = []
    for seed in (42, 43, 44, 45):
        name = f'forecast_lr2e5_s{seed}'
        raw = (lroot / f'runs/{name}/component_results/qwen3_8b_sft_{name}.summary.json').read_bytes()
        SOURCES[f'learnability/runs/{name}/summary'] = hashlib.sha256(raw).hexdigest()
        cells = {(c['domain'], c['label_kind'], c['interface']): c for c in json.loads(raw)['cells']}
        assert all(c['parse_rate'] == 1 and c['n_pairs'] == 24 for c in cells.values())
        acc = lambda d, l: f"{100*cells[(d, l, 'original')]['accuracy']:.1f}"
        rows.append([str(seed), acc('coin_city', 'semantic'), acc('coin_city', 'arbitrary'),
                     acc('coin_harbor', 'semantic'), acc('coin_harbor', 'arbitrary'),
                     f"{cells[('coin_city', 'semantic', 'original')]['response_mae']:.3f}",
                     f"{100*cells[('coin_city', 'semantic', 'selection_only')]['accuracy']:.0f}"])
    write('exp3_learnability_seeds.tex', 'lrrrrrr',
          r'Seed & City/sem. & City/arb. & Harbor/sem. & Harbor/arb. & Resp. MAE & Name (\%)', rows)

    # Native-cell SFT: each cell trained in its own domain/label condition.
    native_root = ROOT / 'native_cells'
    NATIVE = [('coin_city','arbitrary'), ('coin_harbor','semantic'), ('coin_harbor','arbitrary')]
    rows = []
    for domain, labels in NATIVE:
        seeds = []
        for seed in (42,43,44):
            name = f'native_{domain}_{labels}_s{seed}'
            raw = (native_root / f'runs/{name}/component_results/qwen3_8b_{name}.summary.json').read_bytes()
            SOURCES[f'native_cells/runs/{name}/summary'] = hashlib.sha256(raw).hexdigest()
            cells = json.loads(raw)['cells']
            own = {c['interface']: c for c in cells
                   if (c['domain'], c['label_kind']) == (domain, labels)}
            assert own['original']['n_pairs'] == 24 and own['original']['parse_rate'] == 1
            seeds.append((own['original'], own['selection_only']))
        assert len(seeds) == 3
        acc = mean(o['accuracy'] for o, _ in seeds)
        mae = mean(o['response_mae'] for o, _ in seeds)
        sel = mean(s_['accuracy'] for _, s_ in seeds)
        lo = min(o['accuracy'] for o, _ in seeds); hi = max(o['accuracy'] for o, _ in seeds)
        rows.append([domain.removeprefix('coin_').title(), labels,
                     f'{100*acc:.1f}', f'[{100*lo:.1f}, {100*hi:.1f}]',
                     f'{mae:.3f}', f'{100*sel:.1f}'])
    write('exp3_native_cells.tex', 'llrrrr',
          r'Domain & Labels & Structure (\%) & Seed range & Resp. MAE & Name (\%)', rows)
    (PAPER / 'tables/exp3_diagnostics_sources.json').write_text(json.dumps({
        'generator':'paper/generate_exp3_diagnostic_tables.py', 'artifact_root':str(ROOT.relative_to(PAPER.parent)),
        'source_sha256':SOURCES, 'scope':'Completed exploratory inference and single-seed SFT only; excludes unfinished shuffled training.'},indent=2)+'\n')


if __name__ == '__main__':
    main()
